operations_admin_users: []

operations_control_user: control
operations_control_home: /var/control

operations_platform_user: platform
operations_platform_home: /var/platform

# Use "ssh_keyscan github.com" to generate this string.
operations_known_hosts: ""
operations_known_hosts_path: /etc/ssh/ssh_known_hosts

# Set custom SSH config here.
# This config allows connecting to github repos for the first time without needing known_hosts.
# SSH will warn you if the host changes after that.
#
operations_ssh_config: |
  Host github.com
    StrictHostKeyChecking accept-new

operations_ssh_config_path: /etc/ssh/ssh_config.d/site-runner.conf
