operations_admin_users: []

operations_control_user: control
operations_control_home: /var/control

operations_platform_user: platform
operations_platform_home: /var/platform

# Use "ssh_keyscan github.com" to generate this string.
operations_known_hosts: ""
operations_known_hosts_path: /etc/ssh/ssh_known_hosts
