

operations_ddev_letsencrypt_email: you@example.com

# If using public sites, and you want to use letsencrypt, add this variable.
# See https://ddev.readthedocs.io/en/latest/users/topics/hosting/

# operations_ddev_config_hosting_command: ddev config global --router-bind-all-interfaces --omit-containers=ddev-ssh-agent --use-hardened-images --use-letsencrypt --letsencrypt-email={{ operations_ddev_letsencrypt_email }}
operations_ddev_config_hosting_command: ddev config global --router-bind-all-interfaces --omit-containers=ddev-ssh-agent --use-hardened-images

operations_ddev_service_file_path: "/etc/systemd/system/ddev.service"

operations_ddev_path: "/usr/local/bin"
